### ISSUE TITLE
Collapse contributors with no answers on results pages

### ISSUE THREAD

**Issue by janno42** [fsr-itse/EvaP#631] opened 2015-09-16 15:10 UTC
Contributors who didn't get any answers should be collapsed on the results pages, so that the empty answer lines are not shown.
This should also happen if there are answers in the database, but none of them can be seen by the current user.

![0answers](https://cloud.githubusercontent.com/assets/1781719/9908832/bef82478-5c95-11e5-8b51-78e8f53c7f17.PNG)

**Comment by karyon** [comment] 2015-09-18 07:48
duplicate of #555

**Closed by karyon** 2015-09-18 07:48 UTC
Labels: [C] UI, [P] Minor
