### ISSUE TITLE
When you go back to an evaluation form, the button choices are not remembered

### ISSUE THREAD

**Issue by j4yk** [fsr-itse/EvaP#729] opened 2016-02-07 14:20 UTC
I just tried to submit a form, but was greeted by an SSL error (for whatever unrelated reason). So I "went back" to the form, to find that my unique texts are still there (thank the god of browsers), but I have to reenter all my multiple-choice-answers. Is it possible to improve that or is it entirely in the hands of browser developers?

**Comment by Steditor** [comment] 2016-02-07 17:47
This looks like a duplicate of #715.

**Comment by janno42** [comment] 2016-02-07 17:57
it's not completely the same thing, but #715 would solve the issue, so we could close this one here.
@j4yk what do you think?

**Comment by karyon** [comment] 2016-02-07 18:30
i think we should investigate why the button selection isn't saved by the browser. if i understand it correctly, this should happen by default and we broke it, maybe it's relatively easy to fix.

**Comment by janno42** [comment] 2016-02-07 18:32
it's most likely because the states of the input button-group are handled differently. do you want to have a look at it, @karyon?

**Comment by j4yk** [comment] 2016-02-07 19:02
I agree that #715 would solve the issue, but if karyon is right, investigation might generate interesting insights.

**Comment by karyon** [comment] 2016-02-07 19:03
i tried but couldn't figure it out. here http://getbootstrap.com/javascript/#buttons the button states are restored by firefox when changing to another page and navigating back. but even if i paste their exact code into the student vote page, there the button states are not restored. nevertheless, text fields just work and are restored on evap pages.

**Comment by j4yk** [comment] 2016-02-07 19:53
Chrome does not remember the button state on the bootstrap page either. And as indicated on that page, the Firefox behavior is actually considered a bug, even though it would be helpful in our case.

**Comment by karyon** [comment] 2016-02-07 20:03
i absolutely did not see that warning. in that case, it seems pretty clear to me, browsers shouldn't save the button's state and we're supposed to do that manually, as suggested in #715.

**Closed by karyon** 2016-02-07 20:03 UTC
